name: validate-yaml
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency: renovate
jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Yaml lint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: .github
          yamllint_strict: false
          yamllint_config_datapath: .yamllint

